<?php
include "../includes/menu.php";
?>
<!--conteudo da pagina historia-->
<div class="container place">
<div class="row-fluid">
<div class="col-md-12">

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>Um pouco de História</strong></h4><br>
<p>"No primeiro quartel do período medieval, os "<span style="font-weight:bolder">Collegias Fabrorum"</span> do Império Romano deram origem as associações de artífices de mesmas profissões, e na Alemanha, tais entidades foram denominadas de "<span style="font-weight:bolder">GUILDAS</span> de operários. As associações tinham por escopo guardar os segredos das profissões, e o faziam de modo a serem confiados a poucos, após um demorado tempo de aprendizado. Naquela época, os trabalhadores, reunidos em associações ou Guildas, tinham seus serviços contratados para construção de palácios, catedrais, mausoleus, pontes, etc.</p>
<p>Os maçons da idade lendária e medieval são tidos pelos historiadores como maçons operativos, designação oriunda do trabalho manual de muitos, enquanto o trabalho intelectual era privilégio de poucos. O período moderno ou especulativo surgiu durante o século XVII, quando a construção de catedrais estava em declínio, o que levou muitas <span style="font-weight:bolder">GUILDAS</span> de talhadores de pedra a aceitar, como membros, pessoas de letras eruditas, que deram outro rumo a Maçonaria, tornando-a especulativa. Como não eram profissionais da arte da construção, foram rotulados de "maçons aceitos".</P>
<p>Como resultado dessa evolução importante, teve início a <span style="font-weight:bolder">MAÇONARIA</span>, tal como é hoje conhecida. Em 1717, quatro Lojas Maçonicas, que se reuniam em Londres - Inglaterra, formaram a primeira Grande Loja do Mundo, a qual passou a credenciar outras Lojas e Grandes Lojas em muitos países. O erro da maior parte dos escritores maçonicos consiste na tentativa de basear a história da Instituiçãoo em seu simbolismo. No entanto, a história da Maçoonaria, como a história do mundo, tem a sua base na tradição.</p>
<p>Com frequência, os Maçons classificam a Maçonaria de "Instituição Milenar", porque fazem remontar suas origens a tempos que se perdem na curva enevoada do passado. Contudo, os primórdios da Maçonaria são obscuros, bem como parte de sua história.</p>

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>A Maçonaria no Mundo</strong></h4><br>
<p>Há, aproximadamente, 10 milhões de Maçons distribuídos por mais de 150 Grandes Lojas existente pelo mundo. Destas, 27 Grandes Lojas no Brasil congregam mais de 80.000 maçons. Confrontando o número de Maçons existentes no mundo, com a população inteira do globo, tem-se uma idéia do grau de seletividade adotado para ingresso na Ordem Maçônica. Embora sejamos a maior fraternidade do mundo, não igualamos, em número de adeptos, a qualquer uma das religiões menos difundidas. A força da Maçonaria está na seleção de seus integrantes, escolhidos entre os cidadãos mais expressivos de todos os segmentos da sociedade organizada, irmanados num mesmo sentimento de unidade em torno dos ideais mais elevados da Humanidade, sem fronteiras de raça, cor ou credo.</p>   

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>A Maçonaria no Brasil</strong></h4><br>
<p>Em nosso País, as primeiras Lojas Maçônicas foram formadas por brasileiros que voltavam da Europa, após concluírem seus estudos superiores, permanecendo até o século XIX sem ligação com qualquer Instituição Maçônica. Não existem registros históricos confiáveis sobre essas Lojas Maçônicas, todas formadas com objetivos políticos, pelo que, a rigor, pode-se afirmar que não existiam Lojas Maçônicas no sentido amplo da palavra. Apenas a partir de 1822, que a Maçonaria passou a funcionar como tal em nosso País. Não é objetivo deste informativo entrar em detalhes da história da Maçonaria brasileira, as bibliotecas e livrarias estão bem providas de material informativo sobre o desenvolvimento da fraternidade no Brasil.</p>  

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>O quê é a Maçonaria</strong></h4><br> 
<p>Maçonaria é um movimento filosófico, educativo, filantrópico e progressista que adota a investigação da Verdade, em regime de plena liberdade. Ela é, portanto, uma sociedade formada por livres pensadores, amantes da cultura moral Intelectualmente, este é o seu papel principal, e este caráter explica, em grande parte o notável sucesso que conseguiu. Os ensinamentos maçônicos são ministrados através de rituais que, contém princípios de todas as "Artes Iniciáticas", como o hermetismo, a cabala, o simbolismo, além dos conceitos tradicionais sobre as cores, os números e as lendas antigas.</p>
<p>Nos ritos Maçônicos fundem-se o simbolismo das iniciações primitivas, os ensinamentos Rosa-Cruzes dos antigos filósofos, do pitagorismo, dos templários, do judaísmo, do cristianismo, etc., daí a sua riqueza fora do comum, se comparada a outras instituições fraternas.</p> 
<p>Em sumo, a Maçonaria é uma escola de sabedoria. A admissão na Ordem Maçônica não é, pois, um fim, é um começo, um começo maravilhoso, mas que exige muito trabalho e dedicação.</p>
<p>A Maçonaria é uma instituição que conserva bem viva certas tradições muito antigas de ensinamentos místicos-iniciáticos compostos de rituais simbólicos e de alegorias. O que nela domina é o princípio de tolerância para com as doutrinas religiosas e políticas, porque a Maçonaria está acima e fora das rivalidades que as coloca em conflito.</p>  
<p><strong>Seus lemas fundamentais são:</strong></p>
<p>Liberdade - porque o homen que vence a si mesmo liberta-se da opressão que o escraviza.</p>
<p>Igualdade - porque a Maçonaria reconhece que todos os homens nascem iguais. As principais distinções que admite são o mérito, o talento, a sabedoria, a virtude e o trabalho de cada um.</p>
<p>Fraternidade - porque a Maçonaria aspira que a compreensão reine entre seus adeptos; a Fraternidade diminui os males dos povos e aumenta a compreensão e o respeito entre os homens.</p> 
<p>Sob este prisma, ela pode ser definida de muitas maneiras, mas uma descrição resumida poderia dizer que é uma sociedade destinada ao esforço conjunto de todos, na busca do aperfeiçoamento individual, uma fraternidade dedicada ao aprendizado e ao culto da arte de viver e à construção do caráter.</p>
<p>Não é um clube, nem uma companhia de seguros ou de socorro mútuo. Não é uma organização destinada a patrocinar fóruns de debates políticos e reformas sociais, e o lucro material não está entre seus objetivos, embora os membros da Fraternidade realmente participem de muitos serviços de caridade e obras assistenciais.</p>
<p>Os princípios da Maçonaria são publicamente aclamados, compreendendo: amor fraternal, assistência e lealdade. Em seus ensinamentos são enfatizados os postuladosda mais elevada moral e a prática das virtudes cardeais, proclamadas em todas as eras: temperança, fortaleza, prudência, justiça, fé, esperança e caridade. Seus princípios éticos podem ser aceitos por todos os homens de bem, e a tolerância para com seus semelhantes é assumida por todos os membros.</p>  

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>A Maçonaria não é uma religião?</strong></h4><br>
<p> Não, e não tem a pretensão de tomar o lugar da religião na vida de ninguém. Para ser membro da Maçonaria, o cidadão deve professar uma crença firme em Deus, gozar de boa reputação e ter uma conduta ilibada, independentemente de suas crenças religiosas. O objetivo da Maçonaria é acolher os cidadãos que tenham essas características, ou seja, os bons cidadãos e torná-los ainda melhores - melhor amigo, melhor pai, melhor esposo e melhor irmão. Um bom Maçom é geralmente o melhor membro de sua religião, assim como um bom membro de qualquer religião pode ser um ótimo Maçom. O Maçom vai a sua Loja para aprender a melhor cultivar as virtudes morais em sua vida diária, viver sob a Paternidade de Deus, a Fraternidade dos homens e a Imortalidade da Alma. </p>
<p>Vivendo sob a Paternidade de Deus, aprende a melhor cultivar as elevadas virtudes consagradas pela ética e pela moral; aprendendo a viver em função da Fraternidade entre os homens, desenvolve dentro de si o amor pelo seu semelhante, através da prática desinteressada da caridade. Reconhecendo a grande verdade da Imortalidade de sua Alma, capacita-se como peregrino neste mundo ao seu destino final, na Eternidade.</p> <p>Possui aspecto religioso, porque reconhece a existência de um único princípio criador, regulador, absoluto, supremo e infinito ao qual denomina <span style="font-weight:bolder">GRANDE ARQUITETO DO UNIVERSO</span>, contrapondo-se ao materialismo, fator essencial e indispensável à interpretação verdadeiramente religiosa e lógica do UNIVERSO, base da sustentação e diretriz das doutrinas e atividades maçônicas.</p>

<br>
<span style="font-weight:bolder; font-size:11px; font-style:italic; text-align:right;">Fonte: "Maçonaria um Informativo para quem não é Maçom", publicdo em março de 2005 e republicado em 2014 pela Grande Loja Maçônica do Estado do Acre - GLEAC, por autorização da M.<sup>.</sup>. Resp.<sup>.</sup>. Grande Loja Maçônica do Paraná.</span>  

<h4><img class="gif" src="../img/img3.gif" class="img-responsive" alt="img3"><strong>A Origem dos Três Pontos Maçônicos</strong></h4><br>
<p>Segundo o ir. Luiz Prado em seu livro “Ao Pé das Colunas” no capitulo “A Historicidade do Três Maçônico”, os primeiros aparecerem na Espanha no correr do ano de 1509, com a denominação de “alumbrados”. A fim de que ninguém viesse a compreender suas trocas de cartas, bilhetes ou mensagens escritas, resolveram adotar um modo singular, privativo de identificação, simplificando as palavras escritas e pondo-lhes “três pontinhos” em sentido triangular, substituindo a parte suprimida, cortavam os vocábulos invariavelmente entre uma consoante e uma vogal.</p> 
<p>Nicola Aslan, em seu livro “Estudos Maçônicos Sobre o Simbolismo” define assim: o ponto, do latim punctus, de pungere, é originalmente um sinal ou mancha semelhante ao que deixa uma piada de agulha. Os Maçons usam colocar depois de letras três pontos em forma triangular (.<sup>.</sup>.).  Foi utilizado pela primeira vez, segundo pesquisa de Nicola Aslan, em 12 de agosto de 1774, na França em uma correspondência do G/O/ da França, comunicando mudança de endereço.</p> 
<p>Há quem diga que é uma herança deixada pelos Rosas-Cruzes do século XVII. Embora os três pontos fossem, no início, uma simples forma de abreviatura, não tardaram os simbolistas a se apoderarem dele, transformando-os em símbolo, ao qual foram dadas as mais variadas interpretações. Mas os três pontos, na forma de triangulo eqüilátero, geralmente usado pelos Maçons nas abreviaturas unidos por linhas, produzem o Triângulo, primeira figura das superfícies geométricas e origem da Trigonometria, base de todas as medidas. Por isso, o Triângulo, um dos mais antigos símbolos da humanidade, figurava para os antigos a idéia de geração, de criação. Os três ângulos significavam para eles, os simbolistas, “Sabedoria, Força e Beleza, atributos de Deus, e representavam também o Sol, o Enxofre e o Mercúrio”.</p>   
<p>Falando do número três, podemos dar uma especial atenção aos três pontos que apontamos sobre o nosso nome:<span style="font-weight:bolder"> VONTADE, AMOR OU SABEDORIA, INTELIGÊNCIA.</span> As três qualidades inseparáveis que podem assim ser definidas:</p>
<p><span style="font-weight:bolder"> Vontade:</span> Faculdade de livremente praticar ou deixar de praticar algum ato. Faculdade de querer, de determinar-se. É necessário distinguir do quere, isto é, da decisão que nele é o necessário, e que procede ao que segue. Por conseguinte, o ato voluntário três fases:</p> 
<p>1º - A deliberação, caracterizada por um momento de indecisão, em que o espírito examina as diversas alternativas e as razões favoráveis e desfavoráveis a cada uma das alternativas.</p> 
<p>2º - A decisão que consiste no “eu quero”, o que encerra a deliberação, favorecendo uma das alternativas e eliminando as demais.</p>   
<p>3º - A execução ou realização ativa da escolha feita: esta fase pode faltar nos casos em que impedimos maiores a tornem impossível, sem que isto afete o ato voluntário em si, pois está concentrado formalmente na decisão. Não obstante, vários fatos exteriores podem impedir muitas vezes a realização do mesmo começo daquilo que resolvemos. Mas nem por isso o ato da vontade propriamente dito deixa de existir.</p>

<br>

<span style="font-weight:bolder; font-size:11px; font-style:italic; text-align:right;">Fonte: "Revista "Os Compadres e a Maçonaria no Bujarí", escrita pelo ir.<sup>.</sup>. Raimundo Teixeira Pinto Filho, um dos fundadores da AUG.<sup>.</sup>. EME.<sup>.</sup>. LOJ.<sup>.</sup>. SIMB.<sup>.</sup>. Obreiros da Paz nº 19.</span>  

</div>
</div>
</div>



<?php include "../includes/footer.php"; ?>